### ISSUE TITLE
HasStandardGeneratorsInfo not defined

### ISSUE THREAD

**Issue by jamesjer** [gap-packages/tomlib#25] opened 2019-07-01 15:35 UTC
I maintain a number of GAP packages for the Fedora Linux distribution.  I recently built GAP 4.10.2.  The build log shows error messages of this form for atlasrep and tomlib:

Syntax warning: Unbound global variable in /usr/lib/gap/pkg/atlasrep/gap/test.g:661
        if HasStandardGeneratorsInfo( tom ) then
                                    ^
I grepped through the entire GAP 4.10.2 release, and only found two instances of the name:

./pkg/atlasrep/gap/test.g:        if HasStandardGeneratorsInfo( tom ) then
./pkg/tomlib-1.2.8/gap/tmstdrd.tom:    elif not HasStandardGeneratorsInfo( tom ) then

Where is that supposed to be defined?

**Comment by olexandr-konovalov** [comment] 2019-07-01 21:43
You need to look for `StandardGeneratorsInfo`. If it is defined as an attribute, then GAP automatically defines `HasStandardGeneratorsInfo` which checks whether the object has a value of this attribute bound or not.

**Comment by fingolfin** [comment] 2019-07-02 07:32
`StandardGeneratorsInfo` is defined in `tomlib`, but `atlasrep` 2.1 does not seem to declare any dependency on `tomlib`.

So at least on a first look, this seems like a bug in `atlasrep`  to me. Perhaps @ThomasBreuer could comment?

**Comment by ThomasBreuer** [comment] 2019-07-02 09:04
Yes, `AtlasRep` should not assume that `StandardGeneratorsInfo` is available,
I have to fix this in the next `AtlasRep` version.
(The code line in question cannot be reached when `tomlib` is not loaded,
but still the syntax error message must be avoided.)

When `tomlib` is available then normally one does not see the syntax error message
because `tomlib` is a suggested package of `AtlasRep`.
The only situations where one sees the syntax error message are
that either `tomlib` is not available, or that one loads `AtlasRep` with the
`OnlyNeeded` option (which means to ignore dependencies to other packages
which are not `needed` but only `suggested`).

**Comment by fingolfin** [comment] 2019-07-03 13:40
@ThomasBreuer hmm, I don't see `tomlib` in the AtlasRep 2.1 dependencies at all, not even as a suggested package

**Comment by ThomasBreuer** [comment] 2019-07-03 14:21
@fingolfin `AtlasRep` suggests loading `CTblLib`, and `CTblLib` suggests loading `TomLib`.
Disabling suggested packages works via the global option `OnlyNeeded`,
which means that without this option, suggested packages of suggested packages count themselves as suggested.

**Comment by fingolfin** [comment] 2022-11-04 12:30
I believe this is fixed in the current atlasrep. At least I cannot reproduce it anymore.

**Closed as completed by fingolfin** 2022-11-04 12:30 UTC
Labels: bug

**Comment by ThomasBreuer** [comment] 2022-11-04 12:49
Yes, this is fixed since version 2.1.1 of AtlasRep.
